apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: api-alerts
  namespace: demo
  labels:
    role: alert-rules
    release: kube-prometheus-stack
spec:
  groups:
  - name: api-quality
    rules:
    - alert: ApiHighErrorRate
      expr: sum(rate(flask_http_request_total{status=~"5..", job="api", namespace="demo"}[30s])) / sum(rate(flask_http_request_total{job="api", namespace="demo"}[30s])) > 0.05
      labels:
        severity: critical
      annotations:
        summary: "High HTTP 5xx error rate on api service"
        description: "HTTP 5xx error rate is {{ $value | humanizePercentage }} (above 5% threshold)"
